config/routes.rb
Rails.application.routes.draw do
  root    'sessions#new'
  get     '/login',                     to: 'sessions#new'
  get     '/player_kassenbericht',      to: 'players#kasse'
  post    '/login',                     to: 'sessions#create'
  delete  '/logout',                    to: 'sessions#destroy'
  get     '/change_password',           to: 'players#change_password'
  patch   '/update_password',           to: 'players#password_update'
  get     '/kassenbericht',             to: 'banks#kassenbericht'
  get     '/player_cards',              to: 'players#player_cards'
  get     '/vaccation_overview',        to: 'vaccations#admin_vaccations'
  get     '/admin_show_vaccation',      to: 'vaccations#admin_show'
  get     '/show_potg',                 to: 'player_of_the_games#show_potg'
  get     '/information',               to: 'static_pages#information'
  post    '/update_player_game',        to: 'away_games#update_player'
  get     'cancellations/new'


  resources :withdraws, except: [:show, :index]
  resources :deposits, except: [:show, :index]
  resources :training_sessions_players, except: [:index, :show]
  resources :training_sessions
  resources :players
  resources :player_penalties, except: [:show]
  resources :penalties, except: [:show]
  resources :cards, except: [:show]
  resources :vaccations, except: [:show]
  resources :player_of_the_games, except: [:show]
  resources :away_games
  resources :weekly_training, only: [:show,:index]
end

app/models/player.rb
class Player < ApplicationRecord
  attr_accessor :remember_token, :crop_x, :crop_y, :crop_w, :crop_h
  has_many :training_sessions_players, dependent: :destroy
  has_many :training_sessions, through: :training_sessions_players
  has_many :player_penalties, dependent: :destroy
  has_many :penalties, through: :player_penalties
  has_many :player_away_games, dependent: :destroy
  has_many :vaccations, dependent: :destroy
  has_many :away_games, through: :player_away_games
  has_many :deposits, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :player_of_the_games, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false},length: {minimum:2, maximum:51}
  validates :firstname, presence: true, length: {minimum:2, maximum:20}
  validates :secondname, presence: true, length: {minimum:2, maximum:30}
  mount_uploader :image, ImageUploader
  after_update :crop_image

  has_secure_password

  def crop_image
    image.recreate_versions! if crop_x.present?
  end

  # Returns the hash digest of the given string.
  def Player.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Player.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = Player.new_token
    update_attribute(:remember_digest, Player.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_player
  before_action :require_admin_trainer, except: [:show, :index, :kasse, :password_update, :change_password]
  before_action :require_same_player_or_admin_trainer, only: [:show]
  before_action :set_player, only: [:edit, :update, :show, :destroy]

  def index
    @players = Player.order(:secondname).paginate(page: params[:page], per_page: 10)
  end

  def show
    @training_sessions = TrainingSession.where("date_time <= ? AND date_time >= ?",Date.today.at_end_of_month.next_month,Date.today.at_beginning_of_month.prev_month)
    @training_sessions_not_present = @training_sessions.joins(:players).where("training_sessions_players.player_id": @player.id)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      set_training_possible
      set_roles
      if player_params[:image].present?
        render 'crop'
      elsif player_params[:crop_x].present?
        Cloudinary::Uploader.upload("public#{@player.image.thumb.url}", use_filename: true, unique_filename: false)
        redirect_to @player
      else
        redirect_to @player
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @player.update_attributes(player_params)
      set_roles
      if player_params[:image].present?
        render 'crop'
      elsif player_params[:crop_x].present?
        Cloudinary::Uploader.upload("public#{@player.image.thumb.url}", use_filename: true, unique_filename: false)
        flash[:success] = "Spieler erfolgreich geändert"
        redirect_to players_path
      else
        flash[:success] = "Spieler erfolgreich geändert"
        redirect_to players_path
      end
    else
      render 'edit'
    end
  end

  def destroy
    @player.destroy
    flash[:success] = "Spieler erfolgreich gelöscht"
    redirect_to players_path
  end

  def kasse
    if params.has_key?(:player_id) && is_kassierer_or_admin?
      @player = Player.find(params[:player_id])
    else
      @player = current_player
    end
    @penalties = PlayerPenalty.where("player_id =?",@player.id)
    @deposits = @player.deposits.all
    @kontoverlauf = (@penalties + @deposits).sort_by(&:date).reverse
  end

  def password_update
    @player = current_player
    update_players_password
  end

  def change_password
    @player = current_player
  end

  def player_cards
    @player = current_player
    @cards = @player.cards.paginate(page: params[:page], per_page: 10)
  end

  private
    def set_player
      @player= Player.find(params[:id])
    end

    def password_params
      params.require(:player).permit(:password, :password_confirmation)
    end

    def player_params
      params.require(:player).permit(:firstname,:active,:secondname,:username,:password,:password_confirmation,:image,:crop_x,:crop_y,:crop_w,:crop_h,:cropped)
    end

    def require_same_player_or_admin_trainer
      if logged_in? and params.has_key?(:id)
        if current_player.id != params[:id].to_i and !is_admin? and !is_trainer?
            flash[:danger] = "Du kannst nur deine eigenen Trainingseinheiten ansehen oder du bist admin."
            redirect_to current_player
        end
      else
        flash[:danger] = "Du kannst nur deine eigenen Trainingseinheiten ansehen oder du bist admin."
        redirect_to root_path
      end
    end

    def set_training_possible
        count_possible_training_session = TrainingSession.where("date_time >= ?", @player.created_at).count
        @player.update_attribute(:training_possible,count_possible_training_session)
    end

    def update_players_password
      if !!@player.authenticate(params[:player][:password_old])
        if params[:player][:password].empty?
          flash[:danger] = "Passwort darf nicht leer sein."
          redirect_to change_password_path
        elsif params[:player][:password] != params[:player][:password_confirmation]
          flash[:danger] = "Das neue Passwort stimmt nicht mit der Wiederholung überein."
          redirect_to change_password_path
        elsif @player.update_attributes(password_params)
          flash[:success] = "Passwort erfolgreich geändert."
          redirect_to @player
        else
          redirect_to change_password_path
        end
      else
        flash[:danger] = "Altes Passwort ist falsch."
        redirect_to change_password_path
      end
    end

    def set_roles
      if params.has_key?(:post)
        role = ""
        ["1","2","4","8","16"].each do |n|
          if params[:post][:roles].include?(n)
            role << "1"
          else
            role << "0"
          end
        end
        role= "1" if role.empty?
        @player.update_attribute(:role,role)
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
  def calculate_training_player_percentage(player)
    if is_player?(player)
      calculate_training_percentage(player.training_possible, player.training_not_present)
    else
      "-.- "
    end
  end

  def calculate_training_team_percentage
    training_possible = 0
    training_not_present = 0
    Player.where("role LIKE '1%'").all.each do |p|
      training_possible += p.training_possible
      training_not_present += p.training_not_present
    end
    calculate_training_percentage(training_possible, training_not_present)
  end

  def calculate_training_percentage(possible,not_present)
    if(not_present > possible || possible == 0)
      100
    else
      ((possible - not_present).to_f / possible * 100).round(2)
    end
  end

  def is_player_not_present(player)
    @cancelledPlayer.each do |ps|
      if ps.username == player.username
        return ps
      end
    end
    return nil
  end

end

app/views/players/_box.html.erb
<%= link_to path do %>
<div class="col-md-3 market-update-gd">
  <div class="market-update-block clr-block-1" style="background-color:<%= color %>">

    <div class="col-md-4 market-update-right">
      <i class= "<%= icon %>" ></i>
    </div>

    <div class="col-md-8 market-update-left">
      <h4><%= headline %> </h4>
      <h3 id="<%= id %>"><%= subheadline %></h3>
      <p style="color:white"><%= description %></p>
    </div>

    <div class="clearfix"> </div>

  </div>
</div>
<% end %>

app/views/players/_box_attributes.html.erb
<div class="col-md-10 col-md-offset-1 row" style="display: flex;justify-content: center;">

  <div class="col-md-4 market-update-right">
    <i class= "<%= icon %>"  style="font-size:0.4em;"></i>
  </div>

  <div class="col-md-8 market-update-left mobile_attributes">
    <h4 class="niceBox"> <%= description %></h4>
  </div>

</div>

app/views/players/_calender.html.erb
<!-- Calender -->
<div class="col-md-6 agile-calendar">
    <input type="text" id="example" class="calendar-input" readonly/>
</div>

<script type="text/javascript">
  $(function(){
    //initialize Calendar widget and set parameters
    $('#example').glDatePicker({
      cssName: 'flatwhite',
      showAlways:true,
      specialDates: [
        <% @training_sessions.all.each do |t| %>
        {
          <%  year = t.date_time.year
              month = t.date_time.month-1
              day = t.date_time.day %>
          <%= "date: new Date(#{year},#{month},#{day})," %>
          <% if @training_sessions_not_present.any? {|p| p.id == t.id}  %>
            cssClass: 'player_not_present'
          <% else %>
            cssClass: 'player_present'
          <% end %>
        },
        <% end %>
      ],
      selectableDates: [
        <% @training_sessions.all.each do |t| %>
        {
          <%  year = t.date_time.year
              month = t.date_time.month-1
              day = t.date_time.day%>
          <%= "date: new Date(#{year},#{month},#{day})," %>
        },
        <% end %>
      ],
      onClick: function(target, cell, date, data) {
        var top = parseInt($('.agile-calendar').offset().top)
        $('.gldp-flatwhite').css({ top: top })

        var tag =  date.getDate() + '-';
        var monat = (date.getMonth()+1)+ '-';
        var jahr = date.getFullYear();

        window.location.href = "/training_sessions/show?date="+tag+monat+jahr;
      },
      allowMonthSelect: false,
      allowYearSelect: false,
      prevArrow: '',
      dowOffset: 1,
      nextArrow: ''
    });

    // Set right Position for Calendar, problematic!
    function resize() {
      var height = $('.gldp-flatwhite').height()
      var top = parseInt($('.agile-calendar').offset().top)
      var left = parseInt($('.agile-calendar').offset().left)
      var width = parseInt($('.agile-calendar').width())
      $('.agile-calendar').css({ height: height })
      $('.gldp-flatwhite').css({
                    top: top,
                    left: left+15,
                    minWidth: width-15

      })
    }

    const mq = window.matchMedia( "(max-width: 320px)" );

    resize()

    if( mq.matches){
      var left = parseInt($('.agile-calendar').offset().left)
      $('.gldp-flatwhite').css({
                    left: left
      })
    }

    //Reload Window if windows resize: Update Calendar Posiiton is problematic
    var document_width, document_height;
    $(document).ready(function(){
      document_width=$(document).width();
    });

    $(window).resize(function(){
      if(document_width!=$(document).width()){
        document_width=$(document).width();
        location.reload();
      }
      resize()
    });
  });

</script>

app/views/players/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@player, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', obj: @player %>

      <%= f.label :firstname, "Vorname" %>
      <%= f.text_field :firstname, class: 'form-control' %>

      <%= f.label :secondname, "Nachname" %>
      <%= f.text_field :secondname, class: 'form-control' %>

      <%= f.label :username, "Benutzername" %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :image, "Bild" %>
      <%= f.file_field :image, class: 'form-control' %>

      <% if edit %>
          <label>Aktuelles Bild</label> </br>
          <%= image_tag @player.image.thumb.url %></br></br>
      <% end %>

      <label>Benutzerrollen</label></br>
      <label class="form-check-inline no_indent">
        <input type="checkbox" name="post[roles][]" value="1" <%= "checked" if !edit || (edit && is_player?(@player)) %>>Spieler</label>
      <label class="form-check-inline no_indent">
        <input type="checkbox" name="post[roles][]" id="trainer" value="8" <%= "checked" if edit && is_trainer?(@player) %>>Trainer</label>
      <label class="form-check-inline no_indent">
        <input type="checkbox" name="post[roles][]" id="trainer" value="4" <%= "checked" if edit && is_betreuer?(@player) %>>Betreuer</label>
      <label class="form-check-inline no_indent">
        <input type="checkbox" name="post[roles][]" id="kassierer" value="2" <%= "checked" if edit && is_kassierer?(@player) %>>Kassierer</label>
      <label class="form-check-inline no_indent">
        <input type="checkbox" name="post[roles][]" id="admin" value="16" <%= "checked" if edit && is_admin?(@player) %>>Admin</label>
      <input type="hidden" name="post[roles][]" value="">
      </br></br>


      <%= f.label :active, "Aktiv" %>
      <%= f.check_box :active, class: 'form-control' %>

      <%= f.label :password, "Passwort" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Paswort wiederholen" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit btn, class:"btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/players/_kasse_box.html.erb
<div class="col-md-12" style="background:<%= color %>; margin-top:10px;color:white; border-radius:10px">

    <div class="col-md-2 market-update-right">
      <i class="<%= icon %> bank-icon" style="font-size:1em" ></i>
    </div>

    <div class="col-md-10 market-update-left">
      <h5><%= item.date.to_time.strftime('%d.%m.%Y') %> </h5>
      <% if strafe %>
        <h4><%= item.get_description %></h4>
      <% else %>
        <h4><%= item.get_type %></h4>
      <% end> %>
      <h5><%= number_to_currency(item.get_amount, unit: "") %> €</h5>
    </div>

    <div class="clearfix"> </div>
    
</div>

app/views/players/_kasse_kontoverlauf_table.html.erb
<% @kontoverlauf.each do |d| %>
  <% if d.get_type == "Strafe" %>
    <%= render partial:'kasse_box', locals: {
                                        icon: 'fa fa-minus',
                                        color: "#ff4757",
                                        strafe: true,
                                        item: d
                                      } %>
  <% else %>
    <%= render partial:'kasse_box', locals: {
                                      icon: 'fa fa-plus',
                                      color: "#2ed573",
                                      strafe: false,
                                      item: d
                                    } %>
  <% end %>
<% end %>

app/views/players/_render_boxes.html.erb
<section class="row market">
  <div class="market-updates">
      <%= render  partial:'box',
            locals: { icon: "fa fa-euro-sign",
                      type: "small",
                      color: "#5352ed",
                      headline: "Kontostand",
                      subheadline: "#{number_to_currency(@player.amount, unit: "")} €",
                      description: " ",
                      path: player_kassenbericht_path,
                      id: "kontostand"  }%>
      <%= render  partial:'box',
            locals: { icon: "fa fa-chart-pie",
                      type: "small",
                      color: "#ff4757",
                      headline: "Trainingsbeteiligung",
                      subheadline: "#{calculate_training_player_percentage(@player)}%",
                      description: "(#{@player.training_possible-@player.training_not_present}/#{@player.training_possible})",
                      path: training_sessions_path,
                      id: "trainingsbeteiligung"   }%>

      <%= render  partial:'box',
            locals: { icon: "fa fa-users",
                      type: "small",
                      color: "#2ed573",
                      headline: "Teamstatistik",
                      subheadline: "#{calculate_training_team_percentage}%",
                      description: "",
                      path: training_sessions_path,
                      id: "teamstatistik"   }%>

      <%= render  partial:'box',
            locals: { icon: "fa fa-square",
                      type: "middle",
                      color: "#eccc68",
                      headline: "Gelbe Karten",
                      subheadline: "#{@player.num_cards} Karten",
                      description: "",
                      path: player_cards_path,
                      id: "cards"    }%>
      <div class="clearfix"></div>
  </div>
</section>

app/views/players/change_password.html.erb
<% provide(:title, "Passwort ändern") %>
<h1 class="headline">Passwort ändern</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@player, url: update_password_path) do |f| %>
      <%= render 'shared/error_messages', obj: @player %>

      <%= f.label :password_old, "Altes Passwort" %>
      <%= f.password_field :password_old, class: 'form-control' %>

      <%= f.label :password, "Neues Passwort" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Neues Passwort wiederholen" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.hidden_field :change, value: true %>

      <%= f.submit("Passwort ändern", class: "btn btn-primary btn-lg") %>
    <% end %>
  </div>
</div>

app/views/players/crop.html.erb
<% provide(:title, "Bild zuschneiden") %>
<h1 class="headline">Bild zuschneiden</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= image_tag @player.image.large.url, id:"cropbox" %>

    <h4>Vorschau</h4>
    <div style=" width:100px; height:100px; overflow:hidden; margin-bottom:20px;">
      <%= image_tag @player.image.large.url, id:"preview" %>
    </div>

    <%= form_for @player do |f| %>
      <%= f.hidden_field :crop_x %>
      <%= f.hidden_field :crop_y %>
      <%= f.hidden_field :crop_w %>
      <%= f.hidden_field :crop_h %>
      <%= f.submit "zuschneiden",croped: true, class:"btn btn-primary btn-lg"%>
    <% end %>
    
  </div>
</div>


<script>
  $('#cropbox').Jcrop({
    aspectRatio:1,
    setSelect: [0,0,600,600],
    onSelect: update,
    onChange: update
  });

  function update (coords) {
    $('#player_crop_x').val(coords.x);
    $('#player_crop_y').val(coords.y);
    $('#player_crop_w').val(coords.w);
    $('#player_crop_h').val(coords.h);
    updatePreview(coords);
  }

  function updatePreview (coords){
    $('#preview').css("width",Math.round(100.0/coords.w * $('#cropbox').width()) +'px');
    $('#preview').css("height",Math.round(100.0/coords.h * $('#cropbox').height()) +'px');
    $('#preview').css("margin-left",'-' + Math.round(100.0/coords.w * coords.x) +'px');
    $('#preview').css("margin-top",'-' + Math.round(100.0/coords.h * coords.y) +'px');
  }
</script>

app/views/players/index.html.erb
<% provide(:title, "Spielerübersicht") %>
<h1 class="headline">Spielerübersicht</h1>

<div class="row market-update-gd training_listing">
  <div class="col-md-8 col-md-offset-2">

    <% if is_admin_or_trainer? %>
      <%= link_to "Neuen Spieler hinzufügen",
                new_player_path,
                class: "btn btn-success btn_full_width btn-lg" %>
    <% end %>

    <div class="center" style="margin-bottom:0px">
      <%= will_paginate %>
    </div>

    <% @players.each do |p| %>
      <div class="row player_listing">
        <div class="avatar col-md-2 player_listing_img_div">
          <%= display_avatar(p) %>
        </div>
        <div class="width-row-mobile col-md-9 market-update-left">
          <div class="row">
            <div class="col-md-12">
              <h3 class="player_listing_name"><%= "#{p.firstname} #{p.secondname}" %> </h3>
            </div>
            <div class="col-md-6">
              <%= render partial:'box_attributes',
                          locals: {
                            icon: "fa fa-chart-pie",
                            description: "#{calculate_training_player_percentage(p)}% (#{p.training_possible-p.training_not_present}/#{p.training_possible})"
                          }%>
            </div>
            <div class="col-md-6">
              <%= render partial:'box_attributes',
                          locals: {
                            icon: "fa fa-euro-sign",
                            description: "#{number_to_currency(p.amount, unit: "")} €"
                          }%>
            </div>
            <div class="col-md-6">
              <%= render partial:'box_attributes',
                          locals: {
                            icon: "fa fa-square",
                            description: "#{p.num_cards} Karten"
                          }%>
            </div>
            <div class="col-md-6">
              <%= render partial:'box_attributes',
                          locals: {
                            icon: "fa fa-trophy",
                            description: "#{p.num_potg} mal"
                          }%>
            </div>

            <% if is_admin_or_trainer? %>
              <div class="col-md-6">
                <%= link_to "Spieler bearbeiten",
                            edit_player_path(p),
                            class: "btn btn-warning btn_full_width btn-lg" %>
              </div>
              <div class="col-md-6">
                <%= link_to "Spieler löschen",
                            player_path(p),
                            method: :delete,
                            data: { confirm: "Sicher, dass du den Spieler löschen willst?" },
                            class: "btn btn-danger btn_full_width btn-lg" %>
              </div>
            <% end %>
            <% if is_kassierer_or_admin? %>
              <div class="col-md-6">
                <%= link_to "Kontoverlauf",
                            player_kassenbericht_url(player_id: p.id),
                            class: "btn btn-success btn_full_width btn-lg" %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>

    <div class="center" style="margin-bottom:0px">
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/players/kasse.html.erb
<% provide(:title, "Kassenbericht") %>
<h1 class="headline">Mannschaftskasse</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="col-md-12 center">
      <h3>Kontostand:</h3>
      <h2  id="balance" style="color:<%= @player.amount >= 0? '#2ed573' : '#ff4757' %>; margin-bottom:40px;"><%= number_to_currency(@player.amount, unit: "") %> € </h2>
    </div>

    <div class="col-md-12">
      <%= render partial:'kasse_kontoverlauf_table' %>
    </div>
    
  </div>
</div>


<script type="text/javascript">
  var options = {
    useEasing : true,
    useGrouping : true,
    separator : ',',
    decimal : '.',
    prefix : '',
    suffix : ' €'
  };
  var demo = new CountUp("balance", 0, <%= @player.amount %>, 2, 2.5, options);
  demo.start();
</script>

app/views/players/new.html.erb
<% provide(:title, "Neuer Benutzer") %>
<h1 class="headline">Neuen Benutzer anlegen</h1>

<%= render partial:"form", locals: { btn: "Spieler anlegen", edit: false }%>

app/views/players/player_cards.html.erb
<% provide(:title, "Gelbe Karten Übersicht") %>

<div class="center">
  <h3>Übersicht Gelbe Karten</h3>
  <%= will_paginate @cards %>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Datum</th>
      </tr>
    </thead>
    <tbody>
    <% @cards.each do |c| %>
      <tr>
        <td><%= c.date.to_time.strftime('%d.%m.%Y') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/players/show.html.erb
<% provide(:title, "Home") %>
<section class="main-content">

  <%= render partial:'render_boxes' %>

  <section class="row">
    <%= render partial: 'calender' %>
    <div class="clearfix"></div>
  </section>

</section>

<script type="text/javascript">
  var balance = new CountUp("kontostand", 0, <%= @player.amount %>, 2, 1.5, {suffix : ' €'});
  var solo = new CountUp("trainingsbeteiligung", 0, <%= calculate_training_player_percentage(@player) %>, 2, 1.5, {suffix : ' %'});
  var team = new CountUp("teamstatistik", 0, <%= calculate_training_team_percentage %>, 2, 1.5, {suffix : ' %'});
  var cards = new CountUp("cards", 0, <%= @player.num_cards %>, 0, 2, {suffix : ' Karten'});
  balance.start();
  solo.start();
  team.start();
  cards.start();
</script>